# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"core_test": "00_core.ipynb",
         "template1_test": "01_dstemplate1.ipynb",
         "template2_test": "02_dstemplate2.ipynb",
         "template3_test": "03_dstemplate3.ipynb",
         "ensemble1_test": "08_ensemble1.ipynb",
         "ensemble2_test": "09_ensemble2.ipynb",
         "final_test": "10_final.ipynb",
         "common_test": "11_common.ipynb",
         "vis_test": "12_vis.ipynb",
         "dataproc_test": "13_dataproc.ipynb",
         "data_test": "14_data.ipynb"}

modules = ["core.py",
           "dstemplate1.py",
           "dstemplate2.py",
           "dstemplate3.py",
           "ensemble1.py",
           "ensemble2.py",
           "final.py",
           "common.py",
           "vis.py",
           "dataproc.py",
           "data.py"]

doc_url = "https://hallmx.github.io/nbds_colab/"

git_url = "https://github.com/hallmx/nbds_colab/tree/master/"

def custom_doc_links(name): return None
