# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['core_test']

# Cell
from .final import *
from .vis import *
from .data import *

# Cell
def core_test(test_msg):
  "Function core"
  return test_msg