# AUTOGENERATED! DO NOT EDIT! File to edit: 03_dstemplate3.ipynb (unless otherwise specified).

__all__ = ['template3_test']

# Cell
def template3_test(test_msg):
  "Function template3"
  return test_msg