# AUTOGENERATED! DO NOT EDIT! File to edit: 02_dstemplate2.ipynb (unless otherwise specified).

__all__ = ['template2_test']

# Cell
def template2_test(test_msg):
  "Function template2"
  return test_msg