# AUTOGENERATED! DO NOT EDIT! File to edit: 01_dstemplate1.ipynb (unless otherwise specified).

__all__ = ['template1_test']

# Cell
def template1_test(test_msg):
  "Function template1"
  return test_msg