# AUTOGENERATED! DO NOT EDIT! File to edit: 09_ensemble2.ipynb (unless otherwise specified).

__all__ = ['ensemble2_test']

# Cell

# # Include local library paths
# import sys
# sys.path.append('path/to/local/lib') # put path to local libraries in system path
# Import local libraries # now local libraries in a non_local directory ('lib') can be easily imported

from .common import *
from .vis import *
from .dstemplate1 import *
from .dstemplate2 import *
from .dstemplate3 import *

# Cell
def ensemble2_test(test_msg):
  "Function ensemble2"
  return test_msg