# AUTOGENERATED! DO NOT EDIT! File to edit: 08_ensemble1.ipynb (unless otherwise specified).

__all__ = ['ensemble1_test']

# Cell
def ensemble1_test(test_msg):
  "Function ensemble1"
  return test_msg